// gen-key.js
const { ethers } = require("ethers");
const wallet = ethers.Wallet.createRandom();
console.log("PRIVATE_KEY=", wallet.privateKey);    // 0x...
console.log("ADDRESS=", wallet.address);          // 0x...
